name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
      - name: Set tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"

      - name: Publish Linux
        run: |
          dotnet publish --runtime linux-x64 --no-self-contained src/Chirp.CLI
          zip -rj Chirp.CLI-$tag-linux-x64.zip src/Chirp.CLI/bin/Debug/net7.0/linux-x64/publish/Chirp.CLI
      - name: Publish Windows
        run: |
          dotnet publish --runtime win-x64 --no-self-contained src/Chirp.CLI
          zip -rj Chirp.CLI-$tag-win-x64.zip src/Chirp.CLI/bin/Debug/net7.0/win-x64/publish/Chirp.CLI.exe
      - name: Publish OSX x64
        run: |
          dotnet publish --runtime osx-x64 --no-self-contained src/Chirp.CLI
          zip -rj Chirp.CLI-$tag-osx-x64.zip src/Chirp.CLI/bin/Debug/net7.0/osx-x64/publish/Chirp.CLI
      - name: Publish OSX arm
        run: |
          dotnet publish --runtime osx-arm64 --no-self-contained src/Chirp.CLI
          zip -rj Chirp.CLI-$tag-osx-arm64.zip src/Chirp.CLI/bin/Debug/net7.0/osx-arm64/publish/Chirp.CLI

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Chirp.CLI-${{ env.tag }}-linux-x64.zip
            Chirp.CLI-${{ env.tag }}-win-x64.zip
            Chirp.CLI-${{ env.tag }}-osx-x64.zip
            Chirp.CLI-${{ env.tag }}-osx-arm64.zip