name: Release

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.pull_request.merged == true) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - name: Ensure browsers are installed
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Set tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/ITU-BDSA23-GROUP18/chirp/releases/latest | jq -r .tag_name)
          MAJOR=$(echo $LATEST_TAG | cut -d. -f1  | cut -c 2) 
          MINOR=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH=$(echo $LATEST_TAG | cut -d. -f3)
          echo "tag=v$MAJOR.$MINOR.$(($PATCH + 1))" >> "$GITHUB_ENV"
      - name: Check If Major Release
        if: contains(github.event.pull_request.labels.*.name, 'Major')
        run: |
          echo "tag=v$(($MAJOR + 1)).$MINOR.$PATCH" >> "$GITHUB_ENV"
      - name: Check If Minor Release
        if: contains(github.event.pull_request.labels.*.name, 'Minor')
        run: |
          echo "tag=v$MAJOR.$(($MINOR + 1)).$PATCH" >> "$GITHUB_ENV"

      - name: Publish Linux
        run: |
          dotnet publish --runtime linux-x64 --no-self-contained src/Chirp.Web
          zip -rj Chirp.Razor-$tag-linux-x64.zip src/Chirp.Web/bin/Debug/net7.0/linux-x64/publish/Chirp.Web
      - name: Publish Windows
        run: |
          dotnet publish --runtime win-x64 --no-self-contained src/Chirp.Web
          zip -rj Chirp.Razor-$tag-win-x64.zip src/Chirp.Web/bin/Debug/net7.0/win-x64/publish/Chirp.Web.exe
      - name: Publish OSX x64
        run: |
          dotnet publish --runtime osx-x64 --no-self-contained src/Chirp.Web
          zip -rj Chirp.Razor-$tag-osx-x64.zip src/Chirp.Web/bin/Debug/net7.0/osx-x64/publish/Chirp.Web
      - name: Publish OSX arm
        run: |
          dotnet publish --runtime osx-arm64 --no-self-contained src/Chirp.Web
          zip -rj Chirp.Razor-$tag-osx-arm64.zip src/Chirp.Web/bin/Debug/net7.0/osx-arm64/publish/Chirp.Web

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: |
            Chirp.Razor-${{ env.tag }}-linux-x64.zip
            Chirp.Razor-${{ env.tag }}-win-x64.zip
            Chirp.Razor-${{ env.tag }}-osx-x64.zip
            Chirp.Razor-${{ env.tag }}-osx-arm64.zip
